# Generated by Django 5.2.5 on 2025-09-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Course_details', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Start_date', models.DateField(blank=True, max_length=30, null=True)),
                ('End_date', models.DateField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_id', models.IntegerField(blank=True, null=True)),
                ('User_id', models.IntegerField(blank=True, null=True)),
                ('Result', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Take_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_applied_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_role', models.CharField(blank=True, max_length=30, null=True)),
                ('Resume', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='HRTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, max_length=30, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=30, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='enroll_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_id', models.IntegerField(blank=True, null=True)),
                ('Created_at', models.DateField(blank=True, max_length=30, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='add_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Job_details', models.CharField(blank=True, max_length=30, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('Experience', models.CharField(blank=True, max_length=30, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('email_id', models.CharField(blank=True, max_length=30, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='view_and_enroll_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_id', models.IntegerField(blank=True, null=True)),
                ('Course_details', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Duration', models.CharField(blank=True, max_length=30, null=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.logintable')),
            ],
        ),
    ]
