# Generated by Django 5.2.5 on 2025-09-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_job',
            name='Company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job_applied_users',
            name='Login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareerGuidanceApp.usertable'),
        ),
    ]
