# Generated by Django 5.2.5 on 2025-09-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidanceApp', '0002_manage_job_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_job',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
