# Generated by Django 5.2.5 on 2025-09-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidanceApp', '0003_manage_job_phone_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manage_Job',
            new_name='jobTable',
        ),
    ]
