# Generated by Django 5.2.5 on 2025-09-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidanceApp', '0004_rename_manage_job_jobtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtable',
            name='Company_name',
        ),
    ]
